sudo: required

services:
  - docker

before_install:
  - 'sudo docker build --no-cache --rm -t bats-core-env .'

script:
  - 'sudo docker run -it --rm bats-core ansible-playbook /etc/ansible/roles/bats-core/tests/test.yml'

