sudo: required

services:
  - docker

script:
  - 'sudo docker build --no-cache --rm -t bats-core-env .'
  - 'sudo docker run -it --rm bats-core-env ansible-playbook /etc/ansible/roles/bats-core/tests/test.yml'

