sudo: required

env:
- GIT=git
- GIT=''

services:
  - docker

script:
  - 'sudo docker build --no-cache --rm --build-arg GIT=$GIT -t bats-core-env .'
  - 'sudo docker run -it --rm bats-core-env ansible-playbook /etc/ansible/roles/bats-core/tests/test.yml'
