sudo: required

env:
- ANSIBLE_ARGS="-e @tests/locally_false.json"
- ANSIBLE_ARGS="-e @tests/locally_true.json"

services:
  - docker

script:
  - echo $ANSIBLE_ARG
  - sudo docker build --no-cache -t bats-core-env .
  - sudo docker run -it bats-core-env ansible-playbook /etc/ansible/roles/bats-core/tests/test.yml "$ANSIBLE_ARGS"
