---
# tasks file for bats-core
- name: clone bats-core
  git:
    repo: 'https://github.com/bats-core/bats-core.git'
    dest: "{{ clone_dir }}"

- name: install bats-core from source
  command: ./install.sh /usr/local
  args:
    chdir: "{{ clone_dir }}"

- name: run tests to confirm install
  command: /usr/local/bats /opt/bats/test

