---
# tasks file for bats-core
#- name: check if git is installed
#  command: which git
#  ignore_errors: True
#  register: git_check

- name: clone bats-core
  git:
    repo: "{{ git_repo }}"
    dest: "{{ clone_dir }}"
  when: (clone_locally == false)

- name: clone bats-core locally and copy to host
  import_tasks: clone-locally.yml
  when: (clone_locally != false)

- name: install bats-core from source
  command: ./install.sh /usr/local
  args:
    chdir: "{{ clone_dir }}"

- name: run tests to confirm install
  command: "bats {{ clone_dir }}/test/"
